name: thunder blog deploy
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run docs:build
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: docs/.vuepress/dist


